import type { DeckRecord, FlashcardRecord } from './storage';

// The 5 pre-installed sample decks (App Guide removed — help lives in the modal).
export const SAMPLE_DECKS: DeckRecord[] = [
  { id: 'deck-math',    title: 'Mathematics Sample', isDefault: true },
  { id: 'deck-chem',    title: 'Chemistry Sample',   isDefault: true },
  { id: 'deck-physics', title: 'Physics Sample',     isDefault: true },
  { id: 'deck-history', title: 'History Sample',     isDefault: true },
  { id: 'deck-biology', title: 'Biology Sample',     isDefault: true },
];

function card(
  id: string,
  deckId: string,
  subject: string,
  question: string,
  hint1: string,
  hint2: string,
  solution: string,
): FlashcardRecord {
  return {
    id, deckId, subject, question, hint1, hint2, solution,
    sm2: { ef: 2.5, interval: 1, reps: 0 },
    rating: null,
    lastRated: null,
    nextReviewDate: 0,
  };
}

export const DEFAULT_CARDS: FlashcardRecord[] = [

  // ── Mathematics ────────────────────────────────────────────────────────────
  card('math-1', 'deck-math', 'Mathematics',
    'Evaluate the Gaussian integral: $\\int_0^\\infty e^{-x^2}\\, dx$',
    'Direct integration is impossible — try squaring the integral instead. Let $I^2 = \\int_0^\\infty\\!\\int_0^\\infty e^{-(x^2+y^2)}\\,dx\\,dy$ and convert to polar coordinates.',
    'In polar form the integrand becomes $e^{-r^2}\\cdot r$. The $\\theta$ integral runs from $0$ to $\\tfrac{\\pi}{2}$. Evaluate the $r$ integral with the substitution $u = r^2$.',
    'The polar integral evaluates to $\\dfrac{\\pi}{4}$, so $I^2 = \\dfrac{\\pi}{4}$ and therefore $I = \\dfrac{\\sqrt{\\pi}}{2}$.',
  ),
  card('math-2', 'deck-math', 'Mathematics',
    'Apply integration by parts to evaluate $\\int x e^x\\,dx$.',
    'Use $\\int u\\,dv = uv - \\int v\\,du$. Choose $u = x$ so the polynomial degree drops when you differentiate.',
    'With $u = x$ and $dv = e^x\\,dx$, compute $du = dx$ and $v = e^x$, then substitute into the IBP formula.',
    '$\\int x e^x\\,dx = x e^x - \\int e^x\\,dx = e^x(x - 1) + C$',
  ),
  card('math-3', 'deck-math', 'Mathematics',
    "Evaluate $\\lim_{x \\to 0} \\dfrac{\\sin x}{x}$.",
    "Direct substitution yields the indeterminate form $0/0$. Apply L'Hôpital's rule: differentiate the numerator and denominator separately.",
    "After differentiating: $\\lim_{x \\to 0} \\dfrac{\\cos x}{1}$. Now substitute $x = 0$ directly.",
    '$\\lim_{x \\to 0} \\dfrac{\\sin x}{x} = \\lim_{x \\to 0} \\dfrac{\\cos x}{1} = 1$',
  ),

  // ── Chemistry ─────────────────────────────────────────────────────────────
  card('chem-1', 'deck-chem', 'Chemistry',
    'Balance the combustion of propane: $\\ce{C3H8 + O2 -> CO2 + H2O}$',
    'Balance C and H atoms first, then count oxygens on the product side.',
    '3 carbons give $3\\,\\ce{CO2}$; 8 hydrogens give $4\\,\\ce{H2O}$. Count O on the right: $3 \\times 2 + 4 \\times 1 = 10$.',
    '$\\ce{C3H8 + 5O2 -> 3CO2 + 4H2O}$ — 3 C, 8 H, 10 O each side.',
  ),
  card('chem-2', 'deck-chem', 'Chemistry',
    'What is the relationship between $\\text{pH}$ and $\\text{p}K_a$ at the half-equivalence point of a weak acid titration?',
    'At the half-equivalence point, half the acid has been converted to its conjugate base.',
    'When $[\\text{HA}] = [\\text{A}^-]$, apply the Henderson–Hasselbalch equation.',
    '$\\text{pH} = \\text{p}K_a + \\log\\dfrac{[\\text{A}^-]}{[\\text{HA}]}$. When the ratio is 1, the log term vanishes: $\\text{pH} = \\text{p}K_a$.',
  ),
  card('chem-3', 'deck-chem', 'Chemistry',
    'Use the ideal gas law to find the volume of 2 mol of gas at $300\\,\\text{K}$ and $1\\,\\text{atm}$.',
    'Ideal gas law: $PV = nRT$, where $R = 0.08206\\,\\text{L}\\cdot\\text{atm}/(\\text{mol}\\cdot\\text{K})$.',
    'Rearrange: $V = \\dfrac{nRT}{P}$. Substitute $n = 2$, $T = 300$, $P = 1$.',
    '$V = \\dfrac{2 \\times 0.08206 \\times 300}{1} \\approx 49.2\\,\\text{L}$',
  ),

  // ── Physics ───────────────────────────────────────────────────────────────
  card('phys-1', 'deck-physics', 'Physics',
    "Using Einstein's mass–energy equivalence, how much energy is stored in 1 gram of matter?",
    'Apply $E = mc^2$ where $c \\approx 3 \\times 10^8\\,\\text{m/s}$. Start by converting the mass into SI units (kilograms).',
    'With $m = 1\\,\\text{g} = 10^{-3}\\,\\text{kg}$, compute $c^2 = (3 \\times 10^8)^2 = 9 \\times 10^{16}\\,\\text{m}^2/\\text{s}^2$ and multiply.',
    '$E = mc^2 = (10^{-3})(9 \\times 10^{16}) = 9 \\times 10^{13}\\,\\text{J}$ — roughly 21 kilotons of TNT.',
  ),
  card('phys-2', 'deck-physics', 'Physics',
    'A 5 kg block accelerates at $3\\,\\text{m/s}^2$. What net force acts on it?',
    "State Newton's second law: net force equals mass times acceleration. Identify the two given quantities.",
    'You have $m = 5\\,\\text{kg}$ and $a = 3\\,\\text{m/s}^2$. Substitute directly into $F_{\\text{net}} = ma$.',
    '$F = 5\\,\\text{kg} \\times 3\\,\\text{m/s}^2 = 15\\,\\text{N}$',
  ),
  card('phys-3', 'deck-physics', 'Physics',
    'Calculate the de Broglie wavelength of an electron ($m_e = 9.11 \\times 10^{-31}\\,\\text{kg}$) moving at $v = 2 \\times 10^6\\,\\text{m/s}$.',
    'Use the de Broglie relation $\\lambda = h/p$ where $h = 6.626 \\times 10^{-34}\\,\\text{J}\\cdot\\text{s}$. Momentum $p$ must be found first.',
    'Compute $p = m_e v = 9.11 \\times 10^{-31} \\times 2 \\times 10^6 = 1.822 \\times 10^{-24}\\,\\text{kg}\\cdot\\text{m/s}$, then divide $h$ by $p$.',
    '$\\lambda = \\dfrac{6.626 \\times 10^{-34}}{1.822 \\times 10^{-24}} \\approx 3.64 \\times 10^{-10}\\,\\text{m} = 0.364\\,\\text{nm}$',
  ),

  // ── History ───────────────────────────────────────────────────────────────
  card('hist-1', 'deck-history', 'History',
    'What were the three main underlying causes of the French Revolution (1789)?',
    'Think about the financial, social, and intellectual conditions of 18th-century France.',
    'Consider: state bankruptcy from wars, the rigid Estates system, and Enlightenment ideas.',
    '(1) Financial crisis — war debt and court extravagance bankrupted France. (2) Social inequality — the Third Estate bore all taxes with no political representation. (3) Enlightenment ideas — Locke and Rousseau spread concepts of popular sovereignty that challenged absolute monarchy.',
  ),
  card('hist-2', 'deck-history', 'History',
    "What single event triggered World War I, and why did it escalate so rapidly?",
    'Think about the assassination in Sarajevo and the interlocking alliance system.',
    'Austria-Hungary issued Serbia an ultimatum → partial refusal → declaration of war → Russian mobilisation → German declaration of war on Russia and France.',
    "The assassination of Archduke Franz Ferdinand (28 June 1914) activated the alliance network: Austria-Hungary (backed by Germany) declared war on Serbia; Russia mobilised; Germany's Schlieffen Plan required a two-front war, drawing France and then Britain in within six weeks.",
  ),
  card('hist-3', 'deck-history', 'History',
    'What was the Truman Doctrine (1947) and how did it define US Cold War foreign policy?',
    'It was a direct response to Soviet pressure on Greece and Turkey.',
    "Truman asked Congress to fund resistance to communist insurgencies, framing it as a global commitment.",
    "The Truman Doctrine pledged US support to 'free peoples resisting subjugation.' It shifted US policy from post-war isolationism to active containment, justified by the domino theory — if one country fell to communism, neighbours would follow.",
  ),

  // ── Biology ───────────────────────────────────────────────────────────────
  card('bio-1', 'deck-biology', 'Biology',
    'State the central dogma of molecular biology and name the three known exceptions.',
    'The dogma describes one-way information flow from nucleic acid to protein. Name the two key steps and the molecules transferred at each.',
    'Normal flow: DNA → RNA → Protein. Now consider retroviruses (reverse transcription), RNA viruses (RNA replication), and prions (protein-only propagation) for the exceptions.',
    'Central dogma: DNA → (transcription) → mRNA → (translation) → Protein. Exceptions: (1) reverse transcription (HIV: RNA → DNA via reverse transcriptase), (2) RNA-dependent RNA replication (RNA viruses: RNA → RNA), (3) prion propagation (protein misfolding with no nucleic acid template).',
  ),
  card('bio-2', 'deck-biology', 'Biology',
    'Explain how ATP is synthesised during oxidative phosphorylation in the mitochondria.',
    'Focus on the electron transport chain (Complexes I–IV): how does electron flow drive proton movement across the inner mitochondrial membrane?',
    'H$^+$ accumulates in the intermembrane space, building an electrochemical gradient. ATP synthase (Complex V) harvests this energy as protons flow back into the matrix — this is chemiosmosis.',
    'H$^+$ flows back through ATP synthase (Complex V) down its electrochemical gradient, driving phosphorylation of ADP + P$_\\text{i}$ → ATP. Each NADH yields ~2.5 ATP; each FADH$_2$ ~1.5 ATP.',
  ),
  card('bio-3', 'deck-biology', 'Biology',
    'Two heterozygous plants (Aa × Aa) are crossed. What are the expected phenotypic and genotypic ratios?',
    'Draw the Punnett square for Aa × Aa. Fill each of the four cells with the allele combination from the row and column headers.',
    'The four offspring genotypes are AA, Aa, Aa, and aa. Now apply the rule of complete dominance to collapse these into phenotypes.',
    'Genotypic ratio: 1 AA : 2 Aa : 1 aa. Phenotypic ratio (complete dominance): 3 dominant : 1 recessive.',
  ),
];
